name: neom_onboarding
description: OnBoarding processes for Cyberneom.
version: 1.3.1
homepage: https://github.com/Cyberneom/neom_onboarding
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  neom_commerce:
    git:
      url: git@github.com:emmanuel-montoya/neom_commerce.git
  neom_commons:
    git:
      url: git@github.com:Cyberneom/neom_commons.git
  neom_profile:
    git:
      url: git@github.com:Cyberneom/neom_profile.git
  neom_posts:
    git:
      url: git@github.com:Cyberneom/neom_posts.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
